version: '3.8'

services:
  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '${DATABASE_PORT}:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
